#!/bin/sh

$HOME/.config/polybar/launch.sh 
$HOME/.config/bspwm/scripts/libinput.sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D &

feh --bg-fill ~/Imágenes/Wallpapers/darling-in-the-franxx.png
compton --config /home/efrain/.config/compton/compton.conf &

pkill pa-applet 
pkill nm-applet
pkill cava
pa-applet &
nm-applet &

setxkbmap es &


# Focus siguiento el mouse
bspc config focus_follows_pointer true

bspc config pointer_modifier mod1
bspc monitor -d          

bspc config border_width         1
bspc config window_gap          5
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a URxvt desktop='^1' state=tiled follow=on
bspc rule -a Alacritty desktop='^1' state=floating follow=on
bspc rule -a Pavucontrol desktop='^9' state=tiled follow=on
bspc rule -a Nitrogen desktop='^9' state=tiled follow=on
bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Opera desktop='^2'follow=on
bspc rule -a qutebrowser desktop='^2' follow=on
bspc rule -a Org.gnome.Nautilus desktop='^3' follow=on
bspc rule -a "Spotify" desktop='^4'
bspc rule -a "YouTube Music" desktop='^4'
bspc rule -a Youtube desktop='^4'
bspc rule -a yuna desktop='^4'
bspc rule -a Code desktop='^5'
bspc rule -a discord desktop='^6'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a org.gabmus.giara desktop='^6' state=tiled
bspc rule -a Wpspdf desktop='^7'
bspc rule -a Wps desktop='^7'
bspc rule -a Et desktop='^7'
bspc rule -a Wpp desktop='^7'
bspc rule -a Zathura desktop='^7' state=tiled follow=on
bspc rule -a MEGAsync desktop='^8' follow=on state=floating
bspc rule -a kdeconnect.app desktop='^8' follow=on
bspc rule -a Transmission-gtk desktop='^8' follow=on state=floating
bspc rule -a System-config-printer.py desktop='^8' follow=on state=floating
bspc rule -a Protonvpn-gui desktop='^8' follow=on state=floating
bspc rule -a BlueMail desktop='^8' follow=on state=floating
bspc rule -a Alarm-clock-applet desktop='^9' state=tiled follow=on
bspc rule -a Blueberry.py desktop='^9' follow=on
bspc rule -a Lxappearance desktop='^9' state=tiled follow=on
bspc rule -a Gucharmap desktop='^9' state=tiled follow=on
bspc rule -a Qalculate-gtk desktop='^10' state=tiled follow=on
bspc rule -a GeoGebra desktop='^10' state=fullscreen follow=on
bspc rule -a CrossCode desktop='^10' state=fullscreen follow=on
bspc rule -a SkullGirls desktop='^10' state=fullscreen follow=on
